name: PHPUnit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    #- name: Install dependencies
    #  if: steps.composer-cache.outputs.cache-hit != 'true'
    #  run: composer install --prefer-dist --no-progress --no-suggest
      
    #- name: Run PgSQL tests
    #  run: echo "<?php putenv('host='); putenv(''); putenv(''); putenv(''); putenv('port=');?>" >  && composer exec phpunit tests/PgSQLClassTest.php
      
   # - name: Run SQLite tests
   #   run: composer exec phpunit tests/SQLiteClassTest.php
   # - name: ls
   #   run: ls
